version: 2
registries:
  composer-repository-packages-ciwit-nl:
    type: composer-repository
    url: https://packages.ciwit.nl
    username: ci-agent
    password: "${{secrets.COMPOSER_REPOSITORY_PACKAGES_CIWIT_NL_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "13:30"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - martijnkersloot
  versioning-strategy: increase
  ignore:
  - dependency-name: fresh/doctrine-enum-bundle
    versions:
    - 7.1.3
  - dependency-name: phpstan/phpstan-symfony
    versions:
    - 0.12.25
  - dependency-name: symfony/framework-bundle
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.6
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.70
    - 0.12.73
    - 0.12.75
    - 0.12.76
    - 0.12.78
    - 0.12.80
    - 0.12.81
    - 0.12.82
  - dependency-name: symfony/maker-bundle
    versions:
    - 1.29.0
    - 1.29.1
    - 1.30.0
  - dependency-name: symfony/console
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/security-bundle
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/messenger
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/twig-bundle
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/intl
    versions:
    - 5.2.2
    - 5.2.3
  registries:
  - composer-repository-packages-ciwit-nl
