doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        dbname: '%env(DB_DEFAULT_NAME)%'
        user: '%env(DB_DEFAULT_USER)%'
        password: '%env(DB_DEFAULT_PASS)%'
        types:
            iri:  App\Type\IriType
            version:  App\Type\VersionType
            StudyType:  App\Type\Enum\StudyType
            RecruitmentStatusType:  App\Type\Enum\RecruitmentStatusType
            MethodType:  App\Type\Enum\MethodType
            StructureType:  App\Type\Enum\StructureType
            XsdDataType:  App\Type\Enum\XsdDataType
            StudySource: App\Type\Enum\StudySource
            DependencyCombinatorType: App\Type\Enum\DependencyCombinatorType
            DependencyOperatorType: App\Type\Enum\DependencyOperatorType
            DistributionGenerationStatusType: App\Type\Enum\DistributionGenerationStatusType
            NameOriginType: App\Type\Enum\NameOriginType
            DistributionContentsDependencyType: App\Type\Enum\DistributionContentsDependencyType
            DataDictionaryDataType: App\Type\Enum\DataDictionaryDataType
            PermissionType: App\Type\Enum\PermissionType
            RDFDistributionDatabaseType: App\Type\Enum\RDFDistributionDatabaseType
            MetadataFieldType: App\Type\Enum\MetadataFieldType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Security:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Security'
                prefix: 'App\Security'
                alias: Security
