doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        dbname: '%env(DB_DEFAULT_NAME)%'
        user: '%env(DB_DEFAULT_USER)%'
        password: '%env(DB_DEFAULT_PASS)%'
        types:
            iri:  App\Type\IriType
            StudyType:  App\Type\StudyType
            DistributionAccessType:  App\Type\DistributionAccessType
            RecruitmentStatusType:  App\Type\RecruitmentStatusType
            MethodType:  App\Type\MethodType
            StructureType:  App\Type\StructureType
            XsdDataType:  App\Type\XsdDataType
            version:  App\Type\VersionType
            StudySource: App\Type\StudySource
            DependencyCombinatorType: App\Type\DependencyCombinatorType
            DependencyOperatorType: App\Type\DependencyOperatorType
            DistributionGenerationStatusType: App\Type\DistributionGenerationStatusType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Connection:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Connection'
                prefix: 'App\Connection'
                alias: Connection
            Security:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Security'
                prefix: 'App\Security'
                alias: Security