doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
        types:
            iri:  App\Type\IriType
            StudyType:  App\Type\StudyType
            DistributionAccessType:  App\Type\DistributionAccessType
            RecruitmentStatusType:  App\Type\RecruitmentStatusType
            MethodType:  App\Type\MethodType

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            security:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Security'
                prefix: 'App\Security'
                alias: Security
