hwi_oauth:
    firewall_names: [main]
    http:
        client: guzzle_client.hwi_special
        message_factory: guzzle_client.message_factory
    resource_owners:
        castor:
            type:                oauth2
            client_id:           "%env(CASTOR_API_CLIENT)%"
            client_secret:       "%env(CASTOR_API_SECRET)%"
            access_token_url:    "%env(CASTOR_API_URL)%/oauth/token"
            authorization_url:   "%env(CASTOR_API_URL)%/oauth/authorize"
            infos_url:           "%env(CASTOR_API_URL)%/api/user"
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            options:
                csrf: true
    target_path_parameter: "target_path"