security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        castor:
            id: App\Security\CastorUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: castor
            logout:
                path:       /logout
                target:     /
                invalidate_session: true
            guard:
                authenticators:
                    - App\Security\CastorAuthenticator

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/user, role: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_USER] }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/my-studies, roles: ROLE_USER }