version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docker/mysql/create-import-default.sql:/docker-entrypoint-initdb.d/1-create-import-default.sql:ro

  symfony:
    container_name: symfony
    build:
      context: .
      dockerfile: ./docker/symfony/Dockerfile
    command: php-fpm
    volumes:
      - ./var:/var/www/html/var
      - ~/.composer:/opt/composer
      - .:/home/castor/fdp:delegated
    environment:
      COMPOSER_HOME: /opt/composer
      APP_ENV: dev
    depends_on:
      - mysql
    links:
      - mysql

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - .:/home/castor/fdp:delegated
    depends_on:
      - symfony
    links:
      - mysql