version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0@sha256:d6c8301b7834c5b9c2b733b10b7e630f441af7bc917c74dba379f24eeeb6a313
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - fair-data-point
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - ./docker/mysql/create-import-default.sql:/docker-entrypoint-initdb.d/1-create-import-default.sql:ro

  symfony:
    container_name: symfony
    build:
      context: .
      dockerfile: ./docker/symfony/Dockerfile
    command: php-fpm
    volumes:
      - ~/.composer:/opt/composer
      - .:/home/castor/fdp:delegated
    environment:
      COMPOSER_HOME: /opt/composer
      APP_ENV: dev
    networks:
      - fair-data-point
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql

  init:
    container_name: init
    build:
      context: .
      dockerfile: ./docker/symfony/Dockerfile
    command: /init.sh
    volumes:
      - ~/.composer:/opt/composer
      - .:/home/castor/fdp:delegated
    environment:
      COMPOSER_HOME: /opt/composer
      APP_ENV: dev
      MYSQL_HOST: mysql
    networks:
      - fair-data-point
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - mysql
    links:
      - mysql

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - .:/home/castor/fdp:delegated
    networks:
      - fair-data-point
    depends_on:
      - symfony
    restart: unless-stopped
    links:
      - mysql

networks:
  fair-data-point:
    driver: bridge
    driver_opts:
      # This MTU setting is necessary to allow within-container connectivity when connected to the Castor VPN.
      com.docker.network.driver.mtu: 1445
