all:
  children:
    production:
      hosts:
        oth-nl-prd-fdp02.azure.castoredc.net:
          host_deploy_path: /srv/www/fdp.castoredc.com
          host_key_file: "/home/castor/.ssh/fair-data-point_github.id_ed25519"
          host_composer_path: composer
          releases_to_keep: 5