all:
  children:
    staging:
      hosts:
        fdp-stg-vmweb01.azure.castoredc.net:
          host_deploy_path: /srv/www/fdp.castoredc.dev
          host_key_file: "/home/castor/.ssh/fair-data-point_github.id_ed25519"
          host_composer_path: /home/castor/composer.phar
          releases_to_keep: 10
        fdp-stg-vmweb02.azure.castoredc.net:
          host_deploy_path: /srv/www/fdp.castoredc.dev
          host_key_file: "/home/castor/.ssh/fair-data-point_github.id_ed25519"
          host_composer_path: /home/castor/composer.phar
          releases_to_keep: 10
