version: 2.1

executors:
  php-only:
    docker:
      - image: circleci/php:7.3


jobs:
  unit-tests:
    executor: php-only
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
      - run: composer config --global http-basic.packages.ciwit.nl "${COMPOSER_USER}" "${COMPOSER_PASSWORD}"
      - run: composer install -n -a
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run: vendor/bin/phpunit

  orm-mapping:
    executor: php-only
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
      - run: composer config --global http-basic.packages.ciwit.nl "${COMPOSER_USER}" "${COMPOSER_PASSWORD}"
      - run: composer install -n -a
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run: bin/console doctrine:schema:validate --skip-sync

  phpcs:
    executor: php-only
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
      - run: composer config --global http-basic.packages.ciwit.nl "${COMPOSER_USER}" "${COMPOSER_PASSWORD}"
      - run: composer install -n -a
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run: vendor/bin/phpcs

  phpstan:
    executor: php-only
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
      - run: composer config --global http-basic.packages.ciwit.nl "${COMPOSER_USER}" "${COMPOSER_PASSWORD}"
      - run: composer install -n -a
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run: php -d memory_limit=4G vendor/bin/phpstan analyze

workflows:
  version: 2

  build:
    jobs:
      - unit-tests:
          context: org-global
      - orm-mapping:
          context: org-global
      - phpcs:
          context: org-global
      - phpstan:
          context: org-global
