<?php
declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use function assert;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220317091351 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $connection = $this->connection;
        assert($connection instanceof Connection);

        $result = $connection->executeQuery('SELECT * from migration_versions');
        $count = $result->rowCount();

        if ($count > 0) {
            // Structure already exists, clean up archived versions
            $this->addSql('TRUNCATE migration_versions');
        } else {
            // this up() migration is auto-generated, please modify it to your needs
            $this->addSql('CREATE TABLE affiliation (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', person CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', organization CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', department CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', position VARCHAR(255) NOT NULL, INDEX IDX_EA72153034DCD176 (person), INDEX IDX_EA721530C1EE637C (organization), INDEX IDX_EA721530CD1DE18A (department), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE agent (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, dtype VARCHAR(255) NOT NULL, INDEX slug (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE annotation (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', entity VARCHAR(190) NOT NULL, concept CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_2E443EF2E284468 (entity), INDEX IDX_2E443EF2E74A6050 (concept), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE castor_entity (id VARCHAR(190) NOT NULL, study_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', parent VARCHAR(190) DEFAULT NULL, structure_type VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:StructureType)\', label VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_90006568E7B003E9 (study_id), INDEX IDX_900065683D8E604F (parent), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE castor_institute (id VARCHAR(190) NOT NULL, study_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', country VARCHAR(190) DEFAULT NULL, institute_name VARCHAR(1000) NOT NULL, abbreviation VARCHAR(1000) NOT NULL, code VARCHAR(3) DEFAULT NULL, INDEX IDX_737F0857E7B003E9 (study_id), INDEX IDX_737F08575373C966 (country), PRIMARY KEY(id, study_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE castor_record (record_id VARCHAR(190) NOT NULL, study_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', institute_id VARCHAR(190) NOT NULL, created_on DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_on DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_51CBE91E7B003E9 (study_id), INDEX IDX_51CBE91697B0F4CE7B003E9 (institute_id, study_id), PRIMARY KEY(record_id, study_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE castor_server (id INT NOT NULL, url VARCHAR(255) NOT NULL COMMENT \'(DC2Type:iri)\', name VARCHAR(255) NOT NULL, flag VARCHAR(255) NOT NULL, `default` TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE castor_user (id VARCHAR(190) NOT NULL, user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', name_first VARCHAR(255) NOT NULL, name_middle VARCHAR(255) DEFAULT NULL, name_last VARCHAR(255) NOT NULL, email_address VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_50208F68A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE catalog (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', fdp CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', slug VARCHAR(255) NOT NULL, accept_submissions TINYINT(1) NOT NULL, submission_accesses_data TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, INDEX IDX_1B2C3247E28FB11F (fdp), INDEX IDX_1B2C3247DE12AB56 (created_by), INDEX IDX_1B2C324716FE72E1 (updated_by), INDEX slug (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE catalogs_datasets (catalog_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', dataset_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_1CF6F11DCC3C66FC (catalog_id), INDEX IDX_1CF6F11DD47C2D1B (dataset_id), PRIMARY KEY(catalog_id, dataset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE catalogs_studies (catalog_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', study_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_E1F354EBCC3C66FC (catalog_id), INDEX IDX_E1F354EBE7B003E9 (study_id), PRIMARY KEY(catalog_id, study_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE country (code VARCHAR(190) NOT NULL, castor_country_id VARCHAR(255) NOT NULL, abbreviation VARCHAR(255) NOT NULL, tld VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, INDEX castorCountryId (castor_country_id), PRIMARY KEY(code)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_dictionary (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_dictionary_group (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_dictionary_option_group (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, INDEX IDX_EAE76F60DE12AB56 (created_by), INDEX IDX_EAE76F6016FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_dictionary_option_option (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', option_group CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, value LONGTEXT NOT NULL, INDEX IDX_FCBD70FC542BF9AD (option_group), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_dictionary_variable (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, format VARCHAR(255) DEFAULT NULL, data_type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:DataDictionaryDataType)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_dictionary_version (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model_module (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model_node (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model_node_external (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', iri VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:iri)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model_node_internal (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', slug VARCHAR(255) NOT NULL, is_repeated TINYINT(1) DEFAULT \'0\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model_node_literal (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', value VARCHAR(255) NOT NULL, data_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model_node_record (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model_node_value (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', is_annotated_value TINYINT(1) NOT NULL, data_type VARCHAR(255) NOT NULL, is_repeated TINYINT(1) DEFAULT \'0\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model_predicate (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', data_model CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', iri VARCHAR(255) NOT NULL COMMENT \'(DC2Type:iri)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, INDEX IDX_7C632AFF992ABE46 (data_model), INDEX IDX_7C632AFFDE12AB56 (created_by), INDEX IDX_7C632AFF16FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model_prefix (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', data_model CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', prefix VARCHAR(255) NOT NULL, uri VARCHAR(255) NOT NULL COMMENT \'(DC2Type:iri)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, INDEX IDX_26A0CAC0992ABE46 (data_model), INDEX IDX_26A0CAC0DE12AB56 (created_by), INDEX IDX_26A0CAC016FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model_triple (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', subject CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', predicate CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', object CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_F13D7030FBCE3E7A (subject), INDEX IDX_F13D7030301BAA7B (predicate), INDEX IDX_F13D7030A8ADABEC (object), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_model_version (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_specification (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, is_public TINYINT(1) DEFAULT \'0\' NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_FF7D0EB0DE12AB56 (created_by), INDEX IDX_FF7D0EB016FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_specification_dependency (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, dtype VARCHAR(255) NOT NULL, INDEX IDX_2AF6C929FE54D947 (group_id), INDEX IDX_2AF6C929DE12AB56 (created_by), INDEX IDX_2AF6C92916FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_specification_dependency_group (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', combinator VARCHAR(255) NOT NULL COMMENT \'(DC2Type:DependencyCombinatorType)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_specification_dependency_rule (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', element CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', operator VARCHAR(255) NOT NULL COMMENT \'(DC2Type:DependencyOperatorType)\', value VARCHAR(255) NOT NULL, INDEX IDX_24BF36441405E39 (element), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_specification_element (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', version CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', option_group CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, orderNumber INT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, groupId CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', type VARCHAR(255) NOT NULL, INDEX IDX_CE19CB2DED8188B0 (groupId), INDEX IDX_CE19CB2DBF1CD3C3 (version), INDEX IDX_CE19CB2D542BF9AD (option_group), INDEX IDX_CE19CB2DDE12AB56 (created_by), INDEX IDX_CE19CB2D16FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_specification_elementgroup (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, groupId CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', type VARCHAR(255) NOT NULL, INDEX IDX_B353A448ED8188B0 (groupId), INDEX IDX_B353A448DE12AB56 (created_by), INDEX IDX_B353A44816FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_specification_group (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', version CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', dependencies CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) NOT NULL, orderNumber INT DEFAULT NULL, is_repeated TINYINT(1) DEFAULT \'0\' NOT NULL, is_dependent TINYINT(1) DEFAULT \'0\' NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_65CF49E1BF1CD3C3 (version), UNIQUE INDEX UNIQ_65CF49E1EA0F708D (dependencies), INDEX IDX_65CF49E1DE12AB56 (created_by), INDEX IDX_65CF49E116FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_specification_mappings (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', study CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', version CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_C7FCEF1E67F9749 (study), INDEX IDX_C7FCEF1BF1CD3C3 (version), INDEX IDX_C7FCEF1DE12AB56 (created_by), INDEX IDX_C7FCEF116FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_specification_mappings_element (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', element CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', syntax LONGTEXT DEFAULT NULL, transform_data TINYINT(1) NOT NULL, INDEX IDX_A56F1D5341405E39 (element), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE element_mapping_castor_entity (element_mapping_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', castor_entity_id VARCHAR(190) NOT NULL, INDEX IDX_57A8637756AF85A2 (element_mapping_id), INDEX IDX_57A86377380FC0DA (castor_entity_id), PRIMARY KEY(element_mapping_id, castor_entity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_specification_mappings_group (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', entity VARCHAR(190) NOT NULL, groupId CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_55557DF1ED8188B0 (groupId), INDEX IDX_55557DF1E284468 (entity), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE data_specification_version (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', data_specification CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', version VARCHAR(255) NOT NULL COMMENT \'(DC2Type:version)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_304546D7FF7D0EB0 (data_specification), INDEX IDX_304546D7DE12AB56 (created_by), INDEX IDX_304546D716FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dataset (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', study_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', slug VARCHAR(255) NOT NULL, is_published TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, INDEX IDX_B7A041D0E7B003E9 (study_id), INDEX IDX_B7A041D0DE12AB56 (created_by), INDEX IDX_B7A041D016FE72E1 (updated_by), INDEX slug (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE department (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', organization CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', additional_information LONGTEXT DEFAULT NULL, INDEX IDX_CD1DE18AC1EE637C (organization), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE distribution (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', dataset_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', license VARCHAR(190) DEFAULT NULL, user_api CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', slug VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, INDEX IDX_A4483781D47C2D1B (dataset_id), INDEX IDX_A44837815768F419 (license), INDEX IDX_A44837814613B984 (user_api), INDEX IDX_A4483781DE12AB56 (created_by), INDEX IDX_A448378116FE72E1 (updated_by), INDEX slug (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE distribution_contactpoint (distribution_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', agent_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_495112716EB6DDB5 (distribution_id), INDEX IDX_495112713414710B (agent_id), PRIMARY KEY(distribution_id, agent_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE distribution_contents (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', distribution CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', dependencies CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', data_specification CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', data_specification_version CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', access ENUM(\'1\', \'2\', \'3\') NOT NULL COMMENT \'(DC2Type:DistributionAccessType)\', is_published TINYINT(1) NOT NULL, is_cached TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_91757299A4483781 (distribution), UNIQUE INDEX UNIQ_91757299EA0F708D (dependencies), INDEX IDX_91757299FF7D0EB0 (data_specification), INDEX IDX_91757299304546D7 (data_specification_version), INDEX IDX_91757299DE12AB56 (created_by), INDEX IDX_9175729916FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE distribution_csv (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE distribution_databases (distribution CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', database_name VARCHAR(255) NOT NULL, user TEXT NOT NULL, password TEXT NOT NULL, PRIMARY KEY(distribution)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE distribution_dependency (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, dtype VARCHAR(255) NOT NULL, INDEX IDX_3B1E9E0AFE54D947 (group_id), INDEX IDX_3B1E9E0ADE12AB56 (created_by), INDEX IDX_3B1E9E0A16FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE distribution_dependency_group (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', combinator VARCHAR(255) NOT NULL COMMENT \'(DC2Type:DependencyCombinatorType)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE distribution_dependency_rule (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', node CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:DistributionContentsDependencyType)\', operator VARCHAR(255) NOT NULL COMMENT \'(DC2Type:DependencyOperatorType)\', value VARCHAR(255) NOT NULL, INDEX IDX_26D833A3857FE845 (node), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE distribution_rdf (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE fdp (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', iri VARCHAR(255) NOT NULL COMMENT \'(DC2Type:iri)\', purl VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:iri)\', INDEX iri (iri), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE language (code VARCHAR(190) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(code)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE license (slug VARCHAR(190) NOT NULL, url VARCHAR(255) NOT NULL COMMENT \'(DC2Type:iri)\', name VARCHAR(255) NOT NULL, PRIMARY KEY(slug)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE log_generation_distribution (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', distribution CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', status VARCHAR(255) NOT NULL COMMENT \'(DC2Type:DistributionGenerationStatusType)\', errors JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_85B347B0A4483781 (distribution), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE log_generation_distribution_record (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', record VARCHAR(190) NOT NULL, study CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', log CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', status VARCHAR(255) NOT NULL COMMENT \'(DC2Type:DistributionGenerationStatusType)\', errors JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_DDCF39AB9B349F91E67F9749 (record, study), INDEX IDX_DDCF39AB8F3F68C5 (log), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', title CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', description CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', language VARCHAR(190) DEFAULT NULL, license VARCHAR(190) DEFAULT NULL, created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', version VARCHAR(255) NOT NULL COMMENT \'(DC2Type:version)\', landing_page VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:iri)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, dtype VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_4F1434142B36786B (title), UNIQUE INDEX UNIQ_4F1434146DE44026 (description), INDEX IDX_4F143414D4DB71B5 (language), INDEX IDX_4F1434145768F419 (license), INDEX IDX_4F143414DE12AB56 (created_by), INDEX IDX_4F14341416FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_publishers (metadata_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', agent_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_99C06534DC9EE959 (metadata_id), INDEX IDX_99C065343414710B (agent_id), PRIMARY KEY(metadata_id, agent_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dataset_contacts (metadata_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', agent_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_ACD423FADC9EE959 (metadata_id), INDEX IDX_ACD423FA3414710B (agent_id), PRIMARY KEY(metadata_id, agent_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_catalog (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', catalog CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', homepage VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:iri)\', logo VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:iri)\', INDEX IDX_895DE2BF1B2C3247 (catalog), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_catalog_themetaxonomies (catalog_metadata_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', ontology_concept_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_ED914358CD2AC8F7 (catalog_metadata_id), INDEX IDX_ED9143584ACEC524 (ontology_concept_id), PRIMARY KEY(catalog_metadata_id, ontology_concept_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_dataset (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', dataset CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', keyword CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_25D19128B7A041D0 (dataset), UNIQUE INDEX UNIQ_25D191285A93713B (keyword), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_dataset_themes (dataset_metadata_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', ontology_concept_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_E5606EA54C040FE1 (dataset_metadata_id), INDEX IDX_E5606EA54ACEC524 (ontology_concept_id), PRIMARY KEY(dataset_metadata_id, ontology_concept_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_distribution (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', distribution CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_EC1C7F7BA4483781 (distribution), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_fdp (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', fdp CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_9B30AE35E28FB11F (fdp), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_study (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', study_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', studied_condition CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', intervention CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', keyword CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', version VARCHAR(255) NOT NULL COMMENT \'(DC2Type:version)\', brief_name VARCHAR(255) NOT NULL, scientific_name LONGTEXT DEFAULT NULL, brief_summary LONGTEXT DEFAULT NULL, summary LONGTEXT DEFAULT NULL, study_type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:StudyType)\', method_type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:MethodType)\', recruitment_status VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:RecruitmentStatusType)\', estimated_enrollment INT DEFAULT NULL, consent_publish TINYINT(1) DEFAULT NULL, consent_social_media TINYINT(1) DEFAULT NULL, estimated_study_start_date DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', estimated_study_completion_date DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', study_completion_date DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', logo VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:iri)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, INDEX IDX_41C2F2BE7B003E9 (study_id), UNIQUE INDEX UNIQ_41C2F2B9F6690FD (studied_condition), UNIQUE INDEX UNIQ_41C2F2BD11814AB (intervention), UNIQUE INDEX UNIQ_41C2F2B5A93713B (keyword), INDEX IDX_41C2F2BDE12AB56 (created_by), INDEX IDX_41C2F2B16FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_study_conditions (study_metadata_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', ontology_concept_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_4278168091AB1465 (study_metadata_id), INDEX IDX_427816804ACEC524 (ontology_concept_id), PRIMARY KEY(study_metadata_id, ontology_concept_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_study_centers (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', metadata CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', organization CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, INDEX IDX_4F7869194F143414 (metadata), INDEX IDX_4F786919C1EE637C (organization), INDEX IDX_4F786919DE12AB56 (created_by), INDEX IDX_4F78691916FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_study_centers_departments (participating_center_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', department_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_168E7C40D75DAFF6 (participating_center_id), INDEX IDX_168E7C40AE80F5DF (department_id), PRIMARY KEY(participating_center_id, department_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE metadata_study_team (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', metadata CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', person CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', is_contact TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, INDEX IDX_A6D5E8694F143414 (metadata), INDEX IDX_A6D5E86934DCD176 (person), INDEX IDX_A6D5E869DE12AB56 (created_by), INDEX IDX_A6D5E86916FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE ontology (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', url VARCHAR(255) NOT NULL COMMENT \'(DC2Type:iri)\', name VARCHAR(255) NOT NULL, bio_portal_id VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE ontology_concept (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', ontology CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', url VARCHAR(255) NOT NULL COMMENT \'(DC2Type:iri)\', code VARCHAR(255) NOT NULL, display_name VARCHAR(255) NOT NULL, INDEX IDX_5972B8FFDAF05D3 (ontology), INDEX ontology_code (ontology, code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE orcid_user (orcid VARCHAR(255) NOT NULL, user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_D8886EB5A76ED395 (user_id), PRIMARY KEY(orcid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE organization (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', country VARCHAR(190) DEFAULT NULL, homepage VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:iri)\', grid_id VARCHAR(255) DEFAULT NULL, city VARCHAR(255) NOT NULL, coordinates_latitude NUMERIC(10, 8) DEFAULT NULL, coordinates_longitude NUMERIC(11, 8) DEFAULT NULL, INDEX IDX_C1EE637C5373C966 (country), INDEX grid_id (grid_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE permission_catalog (user_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', catalog_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:PermissionType)\', INDEX IDX_2C3DD310A76ED395 (user_id), INDEX IDX_2C3DD310CC3C66FC (catalog_id), PRIMARY KEY(user_id, catalog_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE permission_data_specification (user_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', data_specification_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:PermissionType)\', INDEX IDX_426BAC0EA76ED395 (user_id), INDEX IDX_426BAC0E13281BD0 (data_specification_id), PRIMARY KEY(user_id, data_specification_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE permission_dataset (user_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', dataset_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:PermissionType)\', INDEX IDX_80B1A087A76ED395 (user_id), INDEX IDX_80B1A087D47C2D1B (dataset_id), PRIMARY KEY(user_id, dataset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE permission_distribution (user_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', distribution_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:PermissionType)\', INDEX IDX_CD5B6B74A76ED395 (user_id), INDEX IDX_CD5B6B746EB6DDB5 (distribution_id), PRIMARY KEY(user_id, distribution_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE person (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', first_name VARCHAR(255) NOT NULL, middle_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(255) DEFAULT NULL, orcid VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:iri)\', name_origin VARCHAR(255) NOT NULL COMMENT \'(DC2Type:NameOriginType)\', UNIQUE INDEX UNIQ_34DCD176A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE study (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', source_id VARCHAR(255) DEFAULT NULL, source VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:StudySource)\', name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, entered_manually TINYINT(1) NOT NULL, is_published TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_E67F9749DE12AB56 (created_by), INDEX IDX_E67F974916FE72E1 (updated_by), INDEX slug (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE study_castor (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', server INT DEFAULT NULL, INDEX IDX_4DB9B2045A6DD5F6 (server), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE text_coded (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', text VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE text_localized (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE text_localized_item (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', parent CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', language VARCHAR(190) DEFAULT NULL, text LONGTEXT NOT NULL, INDEX IDX_923CA1F03D8E604F (parent), INDEX IDX_923CA1F0D4DB71B5 (language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE user (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', person_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', castor_user_id VARCHAR(190) DEFAULT NULL, orcid_user_id VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649217BBB47 (person_id), UNIQUE INDEX UNIQ_8D93D649A7F0FBB4 (castor_user_id), UNIQUE INDEX UNIQ_8D93D649BDC9B428 (orcid_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE user_api (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', server INT DEFAULT NULL, email_address VARCHAR(255) NOT NULL, client_id TEXT NOT NULL, client_secret TEXT NOT NULL, INDEX IDX_4613B9845A6DD5F6 (server), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('ALTER TABLE affiliation ADD CONSTRAINT FK_EA72153034DCD176 FOREIGN KEY (person) REFERENCES person (id)');
            $this->addSql('ALTER TABLE affiliation ADD CONSTRAINT FK_EA721530C1EE637C FOREIGN KEY (organization) REFERENCES organization (id)');
            $this->addSql('ALTER TABLE affiliation ADD CONSTRAINT FK_EA721530CD1DE18A FOREIGN KEY (department) REFERENCES department (id)');
            $this->addSql('ALTER TABLE annotation ADD CONSTRAINT FK_2E443EF2E284468 FOREIGN KEY (entity) REFERENCES castor_entity (id)');
            $this->addSql('ALTER TABLE annotation ADD CONSTRAINT FK_2E443EF2E74A6050 FOREIGN KEY (concept) REFERENCES ontology_concept (id)');
            $this->addSql('ALTER TABLE castor_entity ADD CONSTRAINT FK_90006568E7B003E9 FOREIGN KEY (study_id) REFERENCES study_castor (id)');
            $this->addSql('ALTER TABLE castor_entity ADD CONSTRAINT FK_900065683D8E604F FOREIGN KEY (parent) REFERENCES castor_entity (id)');
            $this->addSql('ALTER TABLE castor_institute ADD CONSTRAINT FK_737F0857E7B003E9 FOREIGN KEY (study_id) REFERENCES study_castor (id)');
            $this->addSql('ALTER TABLE castor_institute ADD CONSTRAINT FK_737F08575373C966 FOREIGN KEY (country) REFERENCES country (code)');
            $this->addSql('ALTER TABLE castor_record ADD CONSTRAINT FK_51CBE91E7B003E9 FOREIGN KEY (study_id) REFERENCES study_castor (id)');
            $this->addSql('ALTER TABLE castor_record ADD CONSTRAINT FK_51CBE91697B0F4CE7B003E9 FOREIGN KEY (institute_id, study_id) REFERENCES castor_institute (id, study_id)');
            $this->addSql('ALTER TABLE castor_user ADD CONSTRAINT FK_50208F68A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
            $this->addSql('ALTER TABLE catalog ADD CONSTRAINT FK_1B2C3247E28FB11F FOREIGN KEY (fdp) REFERENCES fdp (id)');
            $this->addSql('ALTER TABLE catalog ADD CONSTRAINT FK_1B2C3247DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE catalog ADD CONSTRAINT FK_1B2C324716FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE catalogs_datasets ADD CONSTRAINT FK_1CF6F11DCC3C66FC FOREIGN KEY (catalog_id) REFERENCES catalog (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE catalogs_datasets ADD CONSTRAINT FK_1CF6F11DD47C2D1B FOREIGN KEY (dataset_id) REFERENCES dataset (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE catalogs_studies ADD CONSTRAINT FK_E1F354EBCC3C66FC FOREIGN KEY (catalog_id) REFERENCES catalog (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE catalogs_studies ADD CONSTRAINT FK_E1F354EBE7B003E9 FOREIGN KEY (study_id) REFERENCES study (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_dictionary ADD CONSTRAINT FK_D095DFFFBF396750 FOREIGN KEY (id) REFERENCES data_specification (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_dictionary_group ADD CONSTRAINT FK_F8ECFBBBF396750 FOREIGN KEY (id) REFERENCES data_specification_group (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_dictionary_option_group ADD CONSTRAINT FK_EAE76F60DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_dictionary_option_group ADD CONSTRAINT FK_EAE76F6016FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_dictionary_option_option ADD CONSTRAINT FK_FCBD70FC542BF9AD FOREIGN KEY (option_group) REFERENCES data_dictionary_option_group (id)');
            $this->addSql('ALTER TABLE data_dictionary_variable ADD CONSTRAINT FK_DB31EFA2BF396750 FOREIGN KEY (id) REFERENCES data_specification_element (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_dictionary_version ADD CONSTRAINT FK_74CABF5DBF396750 FOREIGN KEY (id) REFERENCES data_specification_version (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_model ADD CONSTRAINT FK_992ABE46BF396750 FOREIGN KEY (id) REFERENCES data_specification (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_model_module ADD CONSTRAINT FK_B9356A66BF396750 FOREIGN KEY (id) REFERENCES data_specification_group (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_model_node ADD CONSTRAINT FK_671DFE7BBF396750 FOREIGN KEY (id) REFERENCES data_specification_element (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_model_node_external ADD CONSTRAINT FK_FD7D7D44BF396750 FOREIGN KEY (id) REFERENCES data_specification_element (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_model_node_internal ADD CONSTRAINT FK_AEDCC1FFBF396750 FOREIGN KEY (id) REFERENCES data_specification_element (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_model_node_literal ADD CONSTRAINT FK_B4D5BACFBF396750 FOREIGN KEY (id) REFERENCES data_specification_element (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_model_node_record ADD CONSTRAINT FK_9D711823BF396750 FOREIGN KEY (id) REFERENCES data_specification_element (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_model_node_value ADD CONSTRAINT FK_EE45F571BF396750 FOREIGN KEY (id) REFERENCES data_specification_element (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_model_predicate ADD CONSTRAINT FK_7C632AFF992ABE46 FOREIGN KEY (data_model) REFERENCES data_model_version (id)');
            $this->addSql('ALTER TABLE data_model_predicate ADD CONSTRAINT FK_7C632AFFDE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_model_predicate ADD CONSTRAINT FK_7C632AFF16FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_model_prefix ADD CONSTRAINT FK_26A0CAC0992ABE46 FOREIGN KEY (data_model) REFERENCES data_model_version (id)');
            $this->addSql('ALTER TABLE data_model_prefix ADD CONSTRAINT FK_26A0CAC0DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_model_prefix ADD CONSTRAINT FK_26A0CAC016FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_model_triple ADD CONSTRAINT FK_F13D7030FBCE3E7A FOREIGN KEY (subject) REFERENCES data_model_node (id)');
            $this->addSql('ALTER TABLE data_model_triple ADD CONSTRAINT FK_F13D7030301BAA7B FOREIGN KEY (predicate) REFERENCES data_model_predicate (id)');
            $this->addSql('ALTER TABLE data_model_triple ADD CONSTRAINT FK_F13D7030A8ADABEC FOREIGN KEY (object) REFERENCES data_model_node (id)');
            $this->addSql('ALTER TABLE data_model_triple ADD CONSTRAINT FK_F13D7030BF396750 FOREIGN KEY (id) REFERENCES data_specification_elementgroup (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_model_version ADD CONSTRAINT FK_2ECDAE18BF396750 FOREIGN KEY (id) REFERENCES data_specification_version (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_specification ADD CONSTRAINT FK_FF7D0EB0DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification ADD CONSTRAINT FK_FF7D0EB016FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_dependency ADD CONSTRAINT FK_2AF6C929FE54D947 FOREIGN KEY (group_id) REFERENCES data_specification_dependency_group (id)');
            $this->addSql('ALTER TABLE data_specification_dependency ADD CONSTRAINT FK_2AF6C929DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_dependency ADD CONSTRAINT FK_2AF6C92916FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_dependency_group ADD CONSTRAINT FK_B589FC40BF396750 FOREIGN KEY (id) REFERENCES data_specification_dependency (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_specification_dependency_rule ADD CONSTRAINT FK_24BF36441405E39 FOREIGN KEY (element) REFERENCES data_specification_element (id)');
            $this->addSql('ALTER TABLE data_specification_dependency_rule ADD CONSTRAINT FK_24BF364BF396750 FOREIGN KEY (id) REFERENCES data_specification_dependency (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_specification_element ADD CONSTRAINT FK_CE19CB2DED8188B0 FOREIGN KEY (groupId) REFERENCES data_specification_group (id)');
            $this->addSql('ALTER TABLE data_specification_element ADD CONSTRAINT FK_CE19CB2DBF1CD3C3 FOREIGN KEY (version) REFERENCES data_specification_version (id)');
            $this->addSql('ALTER TABLE data_specification_element ADD CONSTRAINT FK_CE19CB2D542BF9AD FOREIGN KEY (option_group) REFERENCES data_dictionary_option_group (id)');
            $this->addSql('ALTER TABLE data_specification_element ADD CONSTRAINT FK_CE19CB2DDE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_element ADD CONSTRAINT FK_CE19CB2D16FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_elementgroup ADD CONSTRAINT FK_B353A448ED8188B0 FOREIGN KEY (groupId) REFERENCES data_specification_group (id)');
            $this->addSql('ALTER TABLE data_specification_elementgroup ADD CONSTRAINT FK_B353A448DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_elementgroup ADD CONSTRAINT FK_B353A44816FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_group ADD CONSTRAINT FK_65CF49E1BF1CD3C3 FOREIGN KEY (version) REFERENCES data_specification_version (id)');
            $this->addSql('ALTER TABLE data_specification_group ADD CONSTRAINT FK_65CF49E1EA0F708D FOREIGN KEY (dependencies) REFERENCES data_specification_dependency_group (id)');
            $this->addSql('ALTER TABLE data_specification_group ADD CONSTRAINT FK_65CF49E1DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_group ADD CONSTRAINT FK_65CF49E116FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_mappings ADD CONSTRAINT FK_C7FCEF1E67F9749 FOREIGN KEY (study) REFERENCES study (id)');
            $this->addSql('ALTER TABLE data_specification_mappings ADD CONSTRAINT FK_C7FCEF1BF1CD3C3 FOREIGN KEY (version) REFERENCES data_specification_version (id)');
            $this->addSql('ALTER TABLE data_specification_mappings ADD CONSTRAINT FK_C7FCEF1DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_mappings ADD CONSTRAINT FK_C7FCEF116FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_mappings_element ADD CONSTRAINT FK_A56F1D5341405E39 FOREIGN KEY (element) REFERENCES data_specification_element (id)');
            $this->addSql('ALTER TABLE data_specification_mappings_element ADD CONSTRAINT FK_A56F1D53BF396750 FOREIGN KEY (id) REFERENCES data_specification_mappings (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE element_mapping_castor_entity ADD CONSTRAINT FK_57A8637756AF85A2 FOREIGN KEY (element_mapping_id) REFERENCES data_specification_mappings_element (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE element_mapping_castor_entity ADD CONSTRAINT FK_57A86377380FC0DA FOREIGN KEY (castor_entity_id) REFERENCES castor_entity (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_specification_mappings_group ADD CONSTRAINT FK_55557DF1ED8188B0 FOREIGN KEY (groupId) REFERENCES data_specification_group (id)');
            $this->addSql('ALTER TABLE data_specification_mappings_group ADD CONSTRAINT FK_55557DF1E284468 FOREIGN KEY (entity) REFERENCES castor_entity (id)');
            $this->addSql('ALTER TABLE data_specification_mappings_group ADD CONSTRAINT FK_55557DF1BF396750 FOREIGN KEY (id) REFERENCES data_specification_mappings (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE data_specification_version ADD CONSTRAINT FK_304546D7FF7D0EB0 FOREIGN KEY (data_specification) REFERENCES data_specification (id)');
            $this->addSql('ALTER TABLE data_specification_version ADD CONSTRAINT FK_304546D7DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE data_specification_version ADD CONSTRAINT FK_304546D716FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE dataset ADD CONSTRAINT FK_B7A041D0E7B003E9 FOREIGN KEY (study_id) REFERENCES study (id)');
            $this->addSql('ALTER TABLE dataset ADD CONSTRAINT FK_B7A041D0DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE dataset ADD CONSTRAINT FK_B7A041D016FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18AC1EE637C FOREIGN KEY (organization) REFERENCES organization (id)');
            $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18ABF396750 FOREIGN KEY (id) REFERENCES agent (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A4483781D47C2D1B FOREIGN KEY (dataset_id) REFERENCES dataset (id)');
            $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A44837815768F419 FOREIGN KEY (license) REFERENCES license (slug)');
            $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A44837814613B984 FOREIGN KEY (user_api) REFERENCES user_api (id)');
            $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A4483781DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A448378116FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE distribution_contactpoint ADD CONSTRAINT FK_495112716EB6DDB5 FOREIGN KEY (distribution_id) REFERENCES distribution (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE distribution_contactpoint ADD CONSTRAINT FK_495112713414710B FOREIGN KEY (agent_id) REFERENCES agent (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE distribution_contents ADD CONSTRAINT FK_91757299A4483781 FOREIGN KEY (distribution) REFERENCES distribution (id)');
            $this->addSql('ALTER TABLE distribution_contents ADD CONSTRAINT FK_91757299EA0F708D FOREIGN KEY (dependencies) REFERENCES distribution_dependency_group (id)');
            $this->addSql('ALTER TABLE distribution_contents ADD CONSTRAINT FK_91757299FF7D0EB0 FOREIGN KEY (data_specification) REFERENCES data_specification (id)');
            $this->addSql('ALTER TABLE distribution_contents ADD CONSTRAINT FK_91757299304546D7 FOREIGN KEY (data_specification_version) REFERENCES data_specification_version (id)');
            $this->addSql('ALTER TABLE distribution_contents ADD CONSTRAINT FK_91757299DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE distribution_contents ADD CONSTRAINT FK_9175729916FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE distribution_csv ADD CONSTRAINT FK_D815CB1ABF396750 FOREIGN KEY (id) REFERENCES distribution_contents (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE distribution_databases ADD CONSTRAINT FK_8086D1DEA4483781 FOREIGN KEY (distribution) REFERENCES distribution (id)');
            $this->addSql('ALTER TABLE distribution_dependency ADD CONSTRAINT FK_3B1E9E0AFE54D947 FOREIGN KEY (group_id) REFERENCES distribution_dependency_group (id)');
            $this->addSql('ALTER TABLE distribution_dependency ADD CONSTRAINT FK_3B1E9E0ADE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE distribution_dependency ADD CONSTRAINT FK_3B1E9E0A16FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE distribution_dependency_group ADD CONSTRAINT FK_B0AD3893BF396750 FOREIGN KEY (id) REFERENCES distribution_dependency (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE distribution_dependency_rule ADD CONSTRAINT FK_26D833A3857FE845 FOREIGN KEY (node) REFERENCES data_model_node_value (id)');
            $this->addSql('ALTER TABLE distribution_dependency_rule ADD CONSTRAINT FK_26D833A3BF396750 FOREIGN KEY (id) REFERENCES distribution_dependency (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE distribution_rdf ADD CONSTRAINT FK_DDC596AFBF396750 FOREIGN KEY (id) REFERENCES distribution_contents (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE log_generation_distribution ADD CONSTRAINT FK_85B347B0A4483781 FOREIGN KEY (distribution) REFERENCES distribution_contents (id)');
            $this->addSql('ALTER TABLE log_generation_distribution_record ADD CONSTRAINT FK_DDCF39AB9B349F91E67F9749 FOREIGN KEY (record, study) REFERENCES castor_record (record_id, study_id)');
            $this->addSql('ALTER TABLE log_generation_distribution_record ADD CONSTRAINT FK_DDCF39AB8F3F68C5 FOREIGN KEY (log) REFERENCES log_generation_distribution (id)');
            $this->addSql('ALTER TABLE metadata ADD CONSTRAINT FK_4F1434142B36786B FOREIGN KEY (title) REFERENCES text_localized (id)');
            $this->addSql('ALTER TABLE metadata ADD CONSTRAINT FK_4F1434146DE44026 FOREIGN KEY (description) REFERENCES text_localized (id)');
            $this->addSql('ALTER TABLE metadata ADD CONSTRAINT FK_4F143414D4DB71B5 FOREIGN KEY (language) REFERENCES language (code)');
            $this->addSql('ALTER TABLE metadata ADD CONSTRAINT FK_4F1434145768F419 FOREIGN KEY (license) REFERENCES license (slug)');
            $this->addSql('ALTER TABLE metadata ADD CONSTRAINT FK_4F143414DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE metadata ADD CONSTRAINT FK_4F14341416FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE metadata_publishers ADD CONSTRAINT FK_99C06534DC9EE959 FOREIGN KEY (metadata_id) REFERENCES metadata (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_publishers ADD CONSTRAINT FK_99C065343414710B FOREIGN KEY (agent_id) REFERENCES agent (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE dataset_contacts ADD CONSTRAINT FK_ACD423FADC9EE959 FOREIGN KEY (metadata_id) REFERENCES metadata (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE dataset_contacts ADD CONSTRAINT FK_ACD423FA3414710B FOREIGN KEY (agent_id) REFERENCES agent (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_catalog ADD CONSTRAINT FK_895DE2BF1B2C3247 FOREIGN KEY (catalog) REFERENCES catalog (id)');
            $this->addSql('ALTER TABLE metadata_catalog ADD CONSTRAINT FK_895DE2BFBF396750 FOREIGN KEY (id) REFERENCES metadata (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_catalog_themetaxonomies ADD CONSTRAINT FK_ED914358CD2AC8F7 FOREIGN KEY (catalog_metadata_id) REFERENCES metadata_catalog (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_catalog_themetaxonomies ADD CONSTRAINT FK_ED9143584ACEC524 FOREIGN KEY (ontology_concept_id) REFERENCES ontology_concept (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_dataset ADD CONSTRAINT FK_25D19128B7A041D0 FOREIGN KEY (dataset) REFERENCES dataset (id)');
            $this->addSql('ALTER TABLE metadata_dataset ADD CONSTRAINT FK_25D191285A93713B FOREIGN KEY (keyword) REFERENCES text_localized (id)');
            $this->addSql('ALTER TABLE metadata_dataset ADD CONSTRAINT FK_25D19128BF396750 FOREIGN KEY (id) REFERENCES metadata (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_dataset_themes ADD CONSTRAINT FK_E5606EA54C040FE1 FOREIGN KEY (dataset_metadata_id) REFERENCES metadata_dataset (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_dataset_themes ADD CONSTRAINT FK_E5606EA54ACEC524 FOREIGN KEY (ontology_concept_id) REFERENCES ontology_concept (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_distribution ADD CONSTRAINT FK_EC1C7F7BA4483781 FOREIGN KEY (distribution) REFERENCES distribution (id)');
            $this->addSql('ALTER TABLE metadata_distribution ADD CONSTRAINT FK_EC1C7F7BBF396750 FOREIGN KEY (id) REFERENCES metadata (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_fdp ADD CONSTRAINT FK_9B30AE35E28FB11F FOREIGN KEY (fdp) REFERENCES fdp (id)');
            $this->addSql('ALTER TABLE metadata_fdp ADD CONSTRAINT FK_9B30AE35BF396750 FOREIGN KEY (id) REFERENCES metadata (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_study ADD CONSTRAINT FK_41C2F2BE7B003E9 FOREIGN KEY (study_id) REFERENCES study (id)');
            $this->addSql('ALTER TABLE metadata_study ADD CONSTRAINT FK_41C2F2B9F6690FD FOREIGN KEY (studied_condition) REFERENCES text_coded (id)');
            $this->addSql('ALTER TABLE metadata_study ADD CONSTRAINT FK_41C2F2BD11814AB FOREIGN KEY (intervention) REFERENCES text_coded (id)');
            $this->addSql('ALTER TABLE metadata_study ADD CONSTRAINT FK_41C2F2B5A93713B FOREIGN KEY (keyword) REFERENCES text_localized (id)');
            $this->addSql('ALTER TABLE metadata_study ADD CONSTRAINT FK_41C2F2BDE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE metadata_study ADD CONSTRAINT FK_41C2F2B16FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE metadata_study_conditions ADD CONSTRAINT FK_4278168091AB1465 FOREIGN KEY (study_metadata_id) REFERENCES metadata_study (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_study_conditions ADD CONSTRAINT FK_427816804ACEC524 FOREIGN KEY (ontology_concept_id) REFERENCES ontology_concept (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_study_centers ADD CONSTRAINT FK_4F7869194F143414 FOREIGN KEY (metadata) REFERENCES metadata_study (id)');
            $this->addSql('ALTER TABLE metadata_study_centers ADD CONSTRAINT FK_4F786919C1EE637C FOREIGN KEY (organization) REFERENCES organization (id)');
            $this->addSql('ALTER TABLE metadata_study_centers ADD CONSTRAINT FK_4F786919DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE metadata_study_centers ADD CONSTRAINT FK_4F78691916FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE metadata_study_centers_departments ADD CONSTRAINT FK_168E7C40D75DAFF6 FOREIGN KEY (participating_center_id) REFERENCES metadata_study_centers (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_study_centers_departments ADD CONSTRAINT FK_168E7C40AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE metadata_study_team ADD CONSTRAINT FK_A6D5E8694F143414 FOREIGN KEY (metadata) REFERENCES metadata_study (id)');
            $this->addSql('ALTER TABLE metadata_study_team ADD CONSTRAINT FK_A6D5E86934DCD176 FOREIGN KEY (person) REFERENCES person (id)');
            $this->addSql('ALTER TABLE metadata_study_team ADD CONSTRAINT FK_A6D5E869DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE metadata_study_team ADD CONSTRAINT FK_A6D5E86916FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE ontology_concept ADD CONSTRAINT FK_5972B8FFDAF05D3 FOREIGN KEY (ontology) REFERENCES ontology (id)');
            $this->addSql('ALTER TABLE orcid_user ADD CONSTRAINT FK_D8886EB5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
            $this->addSql('ALTER TABLE organization ADD CONSTRAINT FK_C1EE637C5373C966 FOREIGN KEY (country) REFERENCES country (code)');
            $this->addSql('ALTER TABLE organization ADD CONSTRAINT FK_C1EE637CBF396750 FOREIGN KEY (id) REFERENCES agent (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE permission_catalog ADD CONSTRAINT FK_2C3DD310A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
            $this->addSql('ALTER TABLE permission_catalog ADD CONSTRAINT FK_2C3DD310CC3C66FC FOREIGN KEY (catalog_id) REFERENCES catalog (id)');
            $this->addSql('ALTER TABLE permission_data_specification ADD CONSTRAINT FK_426BAC0EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
            $this->addSql('ALTER TABLE permission_data_specification ADD CONSTRAINT FK_426BAC0E13281BD0 FOREIGN KEY (data_specification_id) REFERENCES data_specification (id)');
            $this->addSql('ALTER TABLE permission_dataset ADD CONSTRAINT FK_80B1A087A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
            $this->addSql('ALTER TABLE permission_dataset ADD CONSTRAINT FK_80B1A087D47C2D1B FOREIGN KEY (dataset_id) REFERENCES dataset (id)');
            $this->addSql('ALTER TABLE permission_distribution ADD CONSTRAINT FK_CD5B6B74A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
            $this->addSql('ALTER TABLE permission_distribution ADD CONSTRAINT FK_CD5B6B746EB6DDB5 FOREIGN KEY (distribution_id) REFERENCES distribution (id)');
            $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
            $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176BF396750 FOREIGN KEY (id) REFERENCES agent (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE study ADD CONSTRAINT FK_E67F9749DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE study ADD CONSTRAINT FK_E67F974916FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
            $this->addSql('ALTER TABLE study_castor ADD CONSTRAINT FK_4DB9B2045A6DD5F6 FOREIGN KEY (server) REFERENCES castor_server (id)');
            $this->addSql('ALTER TABLE study_castor ADD CONSTRAINT FK_4DB9B204BF396750 FOREIGN KEY (id) REFERENCES study (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE text_localized_item ADD CONSTRAINT FK_923CA1F03D8E604F FOREIGN KEY (parent) REFERENCES text_localized (id)');
            $this->addSql('ALTER TABLE text_localized_item ADD CONSTRAINT FK_923CA1F0D4DB71B5 FOREIGN KEY (language) REFERENCES language (code)');
            $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649217BBB47 FOREIGN KEY (person_id) REFERENCES person (id)');
            $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649A7F0FBB4 FOREIGN KEY (castor_user_id) REFERENCES castor_user (id)');
            $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649BDC9B428 FOREIGN KEY (orcid_user_id) REFERENCES orcid_user (orcid)');
            $this->addSql('ALTER TABLE user_api ADD CONSTRAINT FK_4613B9845A6DD5F6 FOREIGN KEY (server) REFERENCES castor_server (id)');
        }
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY FK_CD1DE18ABF396750');
        $this->addSql('ALTER TABLE distribution_contactpoint DROP FOREIGN KEY FK_495112713414710B');
        $this->addSql('ALTER TABLE metadata_publishers DROP FOREIGN KEY FK_99C065343414710B');
        $this->addSql('ALTER TABLE dataset_contacts DROP FOREIGN KEY FK_ACD423FA3414710B');
        $this->addSql('ALTER TABLE organization DROP FOREIGN KEY FK_C1EE637CBF396750');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD176BF396750');
        $this->addSql('ALTER TABLE annotation DROP FOREIGN KEY FK_2E443EF2E284468');
        $this->addSql('ALTER TABLE castor_entity DROP FOREIGN KEY FK_900065683D8E604F');
        $this->addSql('ALTER TABLE element_mapping_castor_entity DROP FOREIGN KEY FK_57A86377380FC0DA');
        $this->addSql('ALTER TABLE data_specification_mappings_group DROP FOREIGN KEY FK_55557DF1E284468');
        $this->addSql('ALTER TABLE castor_record DROP FOREIGN KEY FK_51CBE91697B0F4CE7B003E9');
        $this->addSql('ALTER TABLE log_generation_distribution_record DROP FOREIGN KEY FK_DDCF39AB9B349F91E67F9749');
        $this->addSql('ALTER TABLE study_castor DROP FOREIGN KEY FK_4DB9B2045A6DD5F6');
        $this->addSql('ALTER TABLE user_api DROP FOREIGN KEY FK_4613B9845A6DD5F6');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649A7F0FBB4');
        $this->addSql('ALTER TABLE catalogs_datasets DROP FOREIGN KEY FK_1CF6F11DCC3C66FC');
        $this->addSql('ALTER TABLE catalogs_studies DROP FOREIGN KEY FK_E1F354EBCC3C66FC');
        $this->addSql('ALTER TABLE metadata_catalog DROP FOREIGN KEY FK_895DE2BF1B2C3247');
        $this->addSql('ALTER TABLE permission_catalog DROP FOREIGN KEY FK_2C3DD310CC3C66FC');
        $this->addSql('ALTER TABLE castor_institute DROP FOREIGN KEY FK_737F08575373C966');
        $this->addSql('ALTER TABLE organization DROP FOREIGN KEY FK_C1EE637C5373C966');
        $this->addSql('ALTER TABLE data_dictionary_option_option DROP FOREIGN KEY FK_FCBD70FC542BF9AD');
        $this->addSql('ALTER TABLE data_specification_element DROP FOREIGN KEY FK_CE19CB2D542BF9AD');
        $this->addSql('ALTER TABLE data_model_triple DROP FOREIGN KEY FK_F13D7030FBCE3E7A');
        $this->addSql('ALTER TABLE data_model_triple DROP FOREIGN KEY FK_F13D7030A8ADABEC');
        $this->addSql('ALTER TABLE distribution_dependency_rule DROP FOREIGN KEY FK_26D833A3857FE845');
        $this->addSql('ALTER TABLE data_model_triple DROP FOREIGN KEY FK_F13D7030301BAA7B');
        $this->addSql('ALTER TABLE data_model_predicate DROP FOREIGN KEY FK_7C632AFF992ABE46');
        $this->addSql('ALTER TABLE data_model_prefix DROP FOREIGN KEY FK_26A0CAC0992ABE46');
        $this->addSql('ALTER TABLE data_dictionary DROP FOREIGN KEY FK_D095DFFFBF396750');
        $this->addSql('ALTER TABLE data_model DROP FOREIGN KEY FK_992ABE46BF396750');
        $this->addSql('ALTER TABLE data_specification_version DROP FOREIGN KEY FK_304546D7FF7D0EB0');
        $this->addSql('ALTER TABLE distribution_contents DROP FOREIGN KEY FK_91757299FF7D0EB0');
        $this->addSql('ALTER TABLE permission_data_specification DROP FOREIGN KEY FK_426BAC0E13281BD0');
        $this->addSql('ALTER TABLE data_specification_dependency_group DROP FOREIGN KEY FK_B589FC40BF396750');
        $this->addSql('ALTER TABLE data_specification_dependency_rule DROP FOREIGN KEY FK_24BF364BF396750');
        $this->addSql('ALTER TABLE data_specification_dependency DROP FOREIGN KEY FK_2AF6C929FE54D947');
        $this->addSql('ALTER TABLE data_specification_group DROP FOREIGN KEY FK_65CF49E1EA0F708D');
        $this->addSql('ALTER TABLE data_dictionary_variable DROP FOREIGN KEY FK_DB31EFA2BF396750');
        $this->addSql('ALTER TABLE data_model_node DROP FOREIGN KEY FK_671DFE7BBF396750');
        $this->addSql('ALTER TABLE data_model_node_external DROP FOREIGN KEY FK_FD7D7D44BF396750');
        $this->addSql('ALTER TABLE data_model_node_internal DROP FOREIGN KEY FK_AEDCC1FFBF396750');
        $this->addSql('ALTER TABLE data_model_node_literal DROP FOREIGN KEY FK_B4D5BACFBF396750');
        $this->addSql('ALTER TABLE data_model_node_record DROP FOREIGN KEY FK_9D711823BF396750');
        $this->addSql('ALTER TABLE data_model_node_value DROP FOREIGN KEY FK_EE45F571BF396750');
        $this->addSql('ALTER TABLE data_specification_dependency_rule DROP FOREIGN KEY FK_24BF36441405E39');
        $this->addSql('ALTER TABLE data_specification_mappings_element DROP FOREIGN KEY FK_A56F1D5341405E39');
        $this->addSql('ALTER TABLE data_model_triple DROP FOREIGN KEY FK_F13D7030BF396750');
        $this->addSql('ALTER TABLE data_dictionary_group DROP FOREIGN KEY FK_F8ECFBBBF396750');
        $this->addSql('ALTER TABLE data_model_module DROP FOREIGN KEY FK_B9356A66BF396750');
        $this->addSql('ALTER TABLE data_specification_element DROP FOREIGN KEY FK_CE19CB2DED8188B0');
        $this->addSql('ALTER TABLE data_specification_elementgroup DROP FOREIGN KEY FK_B353A448ED8188B0');
        $this->addSql('ALTER TABLE data_specification_mappings_group DROP FOREIGN KEY FK_55557DF1ED8188B0');
        $this->addSql('ALTER TABLE data_specification_mappings_element DROP FOREIGN KEY FK_A56F1D53BF396750');
        $this->addSql('ALTER TABLE data_specification_mappings_group DROP FOREIGN KEY FK_55557DF1BF396750');
        $this->addSql('ALTER TABLE element_mapping_castor_entity DROP FOREIGN KEY FK_57A8637756AF85A2');
        $this->addSql('ALTER TABLE data_dictionary_version DROP FOREIGN KEY FK_74CABF5DBF396750');
        $this->addSql('ALTER TABLE data_model_version DROP FOREIGN KEY FK_2ECDAE18BF396750');
        $this->addSql('ALTER TABLE data_specification_element DROP FOREIGN KEY FK_CE19CB2DBF1CD3C3');
        $this->addSql('ALTER TABLE data_specification_group DROP FOREIGN KEY FK_65CF49E1BF1CD3C3');
        $this->addSql('ALTER TABLE data_specification_mappings DROP FOREIGN KEY FK_C7FCEF1BF1CD3C3');
        $this->addSql('ALTER TABLE distribution_contents DROP FOREIGN KEY FK_91757299304546D7');
        $this->addSql('ALTER TABLE catalogs_datasets DROP FOREIGN KEY FK_1CF6F11DD47C2D1B');
        $this->addSql('ALTER TABLE distribution DROP FOREIGN KEY FK_A4483781D47C2D1B');
        $this->addSql('ALTER TABLE metadata_dataset DROP FOREIGN KEY FK_25D19128B7A041D0');
        $this->addSql('ALTER TABLE permission_dataset DROP FOREIGN KEY FK_80B1A087D47C2D1B');
        $this->addSql('ALTER TABLE affiliation DROP FOREIGN KEY FK_EA721530CD1DE18A');
        $this->addSql('ALTER TABLE metadata_study_centers_departments DROP FOREIGN KEY FK_168E7C40AE80F5DF');
        $this->addSql('ALTER TABLE distribution_contactpoint DROP FOREIGN KEY FK_495112716EB6DDB5');
        $this->addSql('ALTER TABLE distribution_contents DROP FOREIGN KEY FK_91757299A4483781');
        $this->addSql('ALTER TABLE distribution_databases DROP FOREIGN KEY FK_8086D1DEA4483781');
        $this->addSql('ALTER TABLE metadata_distribution DROP FOREIGN KEY FK_EC1C7F7BA4483781');
        $this->addSql('ALTER TABLE permission_distribution DROP FOREIGN KEY FK_CD5B6B746EB6DDB5');
        $this->addSql('ALTER TABLE distribution_csv DROP FOREIGN KEY FK_D815CB1ABF396750');
        $this->addSql('ALTER TABLE distribution_rdf DROP FOREIGN KEY FK_DDC596AFBF396750');
        $this->addSql('ALTER TABLE log_generation_distribution DROP FOREIGN KEY FK_85B347B0A4483781');
        $this->addSql('ALTER TABLE distribution_dependency_group DROP FOREIGN KEY FK_B0AD3893BF396750');
        $this->addSql('ALTER TABLE distribution_dependency_rule DROP FOREIGN KEY FK_26D833A3BF396750');
        $this->addSql('ALTER TABLE distribution_contents DROP FOREIGN KEY FK_91757299EA0F708D');
        $this->addSql('ALTER TABLE distribution_dependency DROP FOREIGN KEY FK_3B1E9E0AFE54D947');
        $this->addSql('ALTER TABLE catalog DROP FOREIGN KEY FK_1B2C3247E28FB11F');
        $this->addSql('ALTER TABLE metadata_fdp DROP FOREIGN KEY FK_9B30AE35E28FB11F');
        $this->addSql('ALTER TABLE metadata DROP FOREIGN KEY FK_4F143414D4DB71B5');
        $this->addSql('ALTER TABLE text_localized_item DROP FOREIGN KEY FK_923CA1F0D4DB71B5');
        $this->addSql('ALTER TABLE distribution DROP FOREIGN KEY FK_A44837815768F419');
        $this->addSql('ALTER TABLE metadata DROP FOREIGN KEY FK_4F1434145768F419');
        $this->addSql('ALTER TABLE log_generation_distribution_record DROP FOREIGN KEY FK_DDCF39AB8F3F68C5');
        $this->addSql('ALTER TABLE metadata_publishers DROP FOREIGN KEY FK_99C06534DC9EE959');
        $this->addSql('ALTER TABLE dataset_contacts DROP FOREIGN KEY FK_ACD423FADC9EE959');
        $this->addSql('ALTER TABLE metadata_catalog DROP FOREIGN KEY FK_895DE2BFBF396750');
        $this->addSql('ALTER TABLE metadata_dataset DROP FOREIGN KEY FK_25D19128BF396750');
        $this->addSql('ALTER TABLE metadata_distribution DROP FOREIGN KEY FK_EC1C7F7BBF396750');
        $this->addSql('ALTER TABLE metadata_fdp DROP FOREIGN KEY FK_9B30AE35BF396750');
        $this->addSql('ALTER TABLE metadata_catalog_themetaxonomies DROP FOREIGN KEY FK_ED914358CD2AC8F7');
        $this->addSql('ALTER TABLE metadata_dataset_themes DROP FOREIGN KEY FK_E5606EA54C040FE1');
        $this->addSql('ALTER TABLE metadata_study_conditions DROP FOREIGN KEY FK_4278168091AB1465');
        $this->addSql('ALTER TABLE metadata_study_centers DROP FOREIGN KEY FK_4F7869194F143414');
        $this->addSql('ALTER TABLE metadata_study_team DROP FOREIGN KEY FK_A6D5E8694F143414');
        $this->addSql('ALTER TABLE metadata_study_centers_departments DROP FOREIGN KEY FK_168E7C40D75DAFF6');
        $this->addSql('ALTER TABLE ontology_concept DROP FOREIGN KEY FK_5972B8FFDAF05D3');
        $this->addSql('ALTER TABLE annotation DROP FOREIGN KEY FK_2E443EF2E74A6050');
        $this->addSql('ALTER TABLE metadata_catalog_themetaxonomies DROP FOREIGN KEY FK_ED9143584ACEC524');
        $this->addSql('ALTER TABLE metadata_dataset_themes DROP FOREIGN KEY FK_E5606EA54ACEC524');
        $this->addSql('ALTER TABLE metadata_study_conditions DROP FOREIGN KEY FK_427816804ACEC524');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649BDC9B428');
        $this->addSql('ALTER TABLE affiliation DROP FOREIGN KEY FK_EA721530C1EE637C');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY FK_CD1DE18AC1EE637C');
        $this->addSql('ALTER TABLE metadata_study_centers DROP FOREIGN KEY FK_4F786919C1EE637C');
        $this->addSql('ALTER TABLE affiliation DROP FOREIGN KEY FK_EA72153034DCD176');
        $this->addSql('ALTER TABLE metadata_study_team DROP FOREIGN KEY FK_A6D5E86934DCD176');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649217BBB47');
        $this->addSql('ALTER TABLE catalogs_studies DROP FOREIGN KEY FK_E1F354EBE7B003E9');
        $this->addSql('ALTER TABLE data_specification_mappings DROP FOREIGN KEY FK_C7FCEF1E67F9749');
        $this->addSql('ALTER TABLE dataset DROP FOREIGN KEY FK_B7A041D0E7B003E9');
        $this->addSql('ALTER TABLE metadata_study DROP FOREIGN KEY FK_41C2F2BE7B003E9');
        $this->addSql('ALTER TABLE study_castor DROP FOREIGN KEY FK_4DB9B204BF396750');
        $this->addSql('ALTER TABLE castor_entity DROP FOREIGN KEY FK_90006568E7B003E9');
        $this->addSql('ALTER TABLE castor_institute DROP FOREIGN KEY FK_737F0857E7B003E9');
        $this->addSql('ALTER TABLE castor_record DROP FOREIGN KEY FK_51CBE91E7B003E9');
        $this->addSql('ALTER TABLE metadata_study DROP FOREIGN KEY FK_41C2F2B9F6690FD');
        $this->addSql('ALTER TABLE metadata_study DROP FOREIGN KEY FK_41C2F2BD11814AB');
        $this->addSql('ALTER TABLE metadata DROP FOREIGN KEY FK_4F1434142B36786B');
        $this->addSql('ALTER TABLE metadata DROP FOREIGN KEY FK_4F1434146DE44026');
        $this->addSql('ALTER TABLE metadata_dataset DROP FOREIGN KEY FK_25D191285A93713B');
        $this->addSql('ALTER TABLE metadata_study DROP FOREIGN KEY FK_41C2F2B5A93713B');
        $this->addSql('ALTER TABLE text_localized_item DROP FOREIGN KEY FK_923CA1F03D8E604F');
        $this->addSql('ALTER TABLE castor_user DROP FOREIGN KEY FK_50208F68A76ED395');
        $this->addSql('ALTER TABLE catalog DROP FOREIGN KEY FK_1B2C3247DE12AB56');
        $this->addSql('ALTER TABLE catalog DROP FOREIGN KEY FK_1B2C324716FE72E1');
        $this->addSql('ALTER TABLE data_dictionary_option_group DROP FOREIGN KEY FK_EAE76F60DE12AB56');
        $this->addSql('ALTER TABLE data_dictionary_option_group DROP FOREIGN KEY FK_EAE76F6016FE72E1');
        $this->addSql('ALTER TABLE data_model_predicate DROP FOREIGN KEY FK_7C632AFFDE12AB56');
        $this->addSql('ALTER TABLE data_model_predicate DROP FOREIGN KEY FK_7C632AFF16FE72E1');
        $this->addSql('ALTER TABLE data_model_prefix DROP FOREIGN KEY FK_26A0CAC0DE12AB56');
        $this->addSql('ALTER TABLE data_model_prefix DROP FOREIGN KEY FK_26A0CAC016FE72E1');
        $this->addSql('ALTER TABLE data_specification DROP FOREIGN KEY FK_FF7D0EB0DE12AB56');
        $this->addSql('ALTER TABLE data_specification DROP FOREIGN KEY FK_FF7D0EB016FE72E1');
        $this->addSql('ALTER TABLE data_specification_dependency DROP FOREIGN KEY FK_2AF6C929DE12AB56');
        $this->addSql('ALTER TABLE data_specification_dependency DROP FOREIGN KEY FK_2AF6C92916FE72E1');
        $this->addSql('ALTER TABLE data_specification_element DROP FOREIGN KEY FK_CE19CB2DDE12AB56');
        $this->addSql('ALTER TABLE data_specification_element DROP FOREIGN KEY FK_CE19CB2D16FE72E1');
        $this->addSql('ALTER TABLE data_specification_elementgroup DROP FOREIGN KEY FK_B353A448DE12AB56');
        $this->addSql('ALTER TABLE data_specification_elementgroup DROP FOREIGN KEY FK_B353A44816FE72E1');
        $this->addSql('ALTER TABLE data_specification_group DROP FOREIGN KEY FK_65CF49E1DE12AB56');
        $this->addSql('ALTER TABLE data_specification_group DROP FOREIGN KEY FK_65CF49E116FE72E1');
        $this->addSql('ALTER TABLE data_specification_mappings DROP FOREIGN KEY FK_C7FCEF1DE12AB56');
        $this->addSql('ALTER TABLE data_specification_mappings DROP FOREIGN KEY FK_C7FCEF116FE72E1');
        $this->addSql('ALTER TABLE data_specification_version DROP FOREIGN KEY FK_304546D7DE12AB56');
        $this->addSql('ALTER TABLE data_specification_version DROP FOREIGN KEY FK_304546D716FE72E1');
        $this->addSql('ALTER TABLE dataset DROP FOREIGN KEY FK_B7A041D0DE12AB56');
        $this->addSql('ALTER TABLE dataset DROP FOREIGN KEY FK_B7A041D016FE72E1');
        $this->addSql('ALTER TABLE distribution DROP FOREIGN KEY FK_A4483781DE12AB56');
        $this->addSql('ALTER TABLE distribution DROP FOREIGN KEY FK_A448378116FE72E1');
        $this->addSql('ALTER TABLE distribution_contents DROP FOREIGN KEY FK_91757299DE12AB56');
        $this->addSql('ALTER TABLE distribution_contents DROP FOREIGN KEY FK_9175729916FE72E1');
        $this->addSql('ALTER TABLE distribution_dependency DROP FOREIGN KEY FK_3B1E9E0ADE12AB56');
        $this->addSql('ALTER TABLE distribution_dependency DROP FOREIGN KEY FK_3B1E9E0A16FE72E1');
        $this->addSql('ALTER TABLE metadata DROP FOREIGN KEY FK_4F143414DE12AB56');
        $this->addSql('ALTER TABLE metadata DROP FOREIGN KEY FK_4F14341416FE72E1');
        $this->addSql('ALTER TABLE metadata_study DROP FOREIGN KEY FK_41C2F2BDE12AB56');
        $this->addSql('ALTER TABLE metadata_study DROP FOREIGN KEY FK_41C2F2B16FE72E1');
        $this->addSql('ALTER TABLE metadata_study_centers DROP FOREIGN KEY FK_4F786919DE12AB56');
        $this->addSql('ALTER TABLE metadata_study_centers DROP FOREIGN KEY FK_4F78691916FE72E1');
        $this->addSql('ALTER TABLE metadata_study_team DROP FOREIGN KEY FK_A6D5E869DE12AB56');
        $this->addSql('ALTER TABLE metadata_study_team DROP FOREIGN KEY FK_A6D5E86916FE72E1');
        $this->addSql('ALTER TABLE orcid_user DROP FOREIGN KEY FK_D8886EB5A76ED395');
        $this->addSql('ALTER TABLE permission_catalog DROP FOREIGN KEY FK_2C3DD310A76ED395');
        $this->addSql('ALTER TABLE permission_data_specification DROP FOREIGN KEY FK_426BAC0EA76ED395');
        $this->addSql('ALTER TABLE permission_dataset DROP FOREIGN KEY FK_80B1A087A76ED395');
        $this->addSql('ALTER TABLE permission_distribution DROP FOREIGN KEY FK_CD5B6B74A76ED395');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD176A76ED395');
        $this->addSql('ALTER TABLE study DROP FOREIGN KEY FK_E67F9749DE12AB56');
        $this->addSql('ALTER TABLE study DROP FOREIGN KEY FK_E67F974916FE72E1');
        $this->addSql('ALTER TABLE distribution DROP FOREIGN KEY FK_A44837814613B984');
        $this->addSql('DROP TABLE affiliation');
        $this->addSql('DROP TABLE agent');
        $this->addSql('DROP TABLE annotation');
        $this->addSql('DROP TABLE castor_entity');
        $this->addSql('DROP TABLE castor_institute');
        $this->addSql('DROP TABLE castor_record');
        $this->addSql('DROP TABLE castor_server');
        $this->addSql('DROP TABLE castor_user');
        $this->addSql('DROP TABLE catalog');
        $this->addSql('DROP TABLE catalogs_datasets');
        $this->addSql('DROP TABLE catalogs_studies');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE data_dictionary');
        $this->addSql('DROP TABLE data_dictionary_group');
        $this->addSql('DROP TABLE data_dictionary_option_group');
        $this->addSql('DROP TABLE data_dictionary_option_option');
        $this->addSql('DROP TABLE data_dictionary_variable');
        $this->addSql('DROP TABLE data_dictionary_version');
        $this->addSql('DROP TABLE data_model');
        $this->addSql('DROP TABLE data_model_module');
        $this->addSql('DROP TABLE data_model_node');
        $this->addSql('DROP TABLE data_model_node_external');
        $this->addSql('DROP TABLE data_model_node_internal');
        $this->addSql('DROP TABLE data_model_node_literal');
        $this->addSql('DROP TABLE data_model_node_record');
        $this->addSql('DROP TABLE data_model_node_value');
        $this->addSql('DROP TABLE data_model_predicate');
        $this->addSql('DROP TABLE data_model_prefix');
        $this->addSql('DROP TABLE data_model_triple');
        $this->addSql('DROP TABLE data_model_version');
        $this->addSql('DROP TABLE data_specification');
        $this->addSql('DROP TABLE data_specification_dependency');
        $this->addSql('DROP TABLE data_specification_dependency_group');
        $this->addSql('DROP TABLE data_specification_dependency_rule');
        $this->addSql('DROP TABLE data_specification_element');
        $this->addSql('DROP TABLE data_specification_elementgroup');
        $this->addSql('DROP TABLE data_specification_group');
        $this->addSql('DROP TABLE data_specification_mappings');
        $this->addSql('DROP TABLE data_specification_mappings_element');
        $this->addSql('DROP TABLE element_mapping_castor_entity');
        $this->addSql('DROP TABLE data_specification_mappings_group');
        $this->addSql('DROP TABLE data_specification_version');
        $this->addSql('DROP TABLE dataset');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE distribution');
        $this->addSql('DROP TABLE distribution_contactpoint');
        $this->addSql('DROP TABLE distribution_contents');
        $this->addSql('DROP TABLE distribution_csv');
        $this->addSql('DROP TABLE distribution_databases');
        $this->addSql('DROP TABLE distribution_dependency');
        $this->addSql('DROP TABLE distribution_dependency_group');
        $this->addSql('DROP TABLE distribution_dependency_rule');
        $this->addSql('DROP TABLE distribution_rdf');
        $this->addSql('DROP TABLE fdp');
        $this->addSql('DROP TABLE language');
        $this->addSql('DROP TABLE license');
        $this->addSql('DROP TABLE log_generation_distribution');
        $this->addSql('DROP TABLE log_generation_distribution_record');
        $this->addSql('DROP TABLE metadata');
        $this->addSql('DROP TABLE metadata_publishers');
        $this->addSql('DROP TABLE dataset_contacts');
        $this->addSql('DROP TABLE metadata_catalog');
        $this->addSql('DROP TABLE metadata_catalog_themetaxonomies');
        $this->addSql('DROP TABLE metadata_dataset');
        $this->addSql('DROP TABLE metadata_dataset_themes');
        $this->addSql('DROP TABLE metadata_distribution');
        $this->addSql('DROP TABLE metadata_fdp');
        $this->addSql('DROP TABLE metadata_study');
        $this->addSql('DROP TABLE metadata_study_conditions');
        $this->addSql('DROP TABLE metadata_study_centers');
        $this->addSql('DROP TABLE metadata_study_centers_departments');
        $this->addSql('DROP TABLE metadata_study_team');
        $this->addSql('DROP TABLE ontology');
        $this->addSql('DROP TABLE ontology_concept');
        $this->addSql('DROP TABLE orcid_user');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE permission_catalog');
        $this->addSql('DROP TABLE permission_data_specification');
        $this->addSql('DROP TABLE permission_dataset');
        $this->addSql('DROP TABLE permission_distribution');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE study');
        $this->addSql('DROP TABLE study_castor');
        $this->addSql('DROP TABLE text_coded');
        $this->addSql('DROP TABLE text_localized');
        $this->addSql('DROP TABLE text_localized_item');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_api');
    }
}
